#!/usr/bin/env bash

reset="\e[0m";
black="\e[1;30m";
blue="\e[1;34m";
cyan="\e[1;36m";
green="\e[1;32;27m";
orange="\e[1;33;27m";
purple="\e[1;35m";
red="\e[1;31m";
violet="\e[1;35";
white="\e[1;37;27m";
yellow="\e[1;33;27m";

# Highlight the user name when logged in as root
if [[ "${USER}" == "root" ]]; then
    userStyle="${red}";
else
    userStyle="${orange}";
fi;

# Highlight the hostname when connected via SSH
if [[ "${SSH_TTY}" ]]; then
    hostStyle="${red}";
else
    hostStyle="${yellow}";
fi;

# Set the terminal title and prompt
PS1="\[${blue}\]\u"; # username
PS1+="\[${white}\] at ";
PS1+="\[${cyan}\]\h"; # host
PS1+="\[${white}\] in ";
PS1+="\[${green}\]\w"; # working directory full path
PS1+="\n";
PS1+="\[${white}\]\$ \[${reset}\]"; # '$' and reset color
export PS1;

PS2="\[${yellow}]> \[${reset}\]";
export PS2;
