" Based on the vimrc by Doug Black http://dougblack.io/words/a-good-vimrc.html

"###### Color and syntax ######
colorscheme badwolf	" color scheme from Steve Losh http://stevelosh.com/projects/badwolf
syntax enable		" enable syntax processing

"###### Spaces and Tabs ######
" default settings
set tabstop=4		" number of visual spaces per tab when reading in tabs
set shiftwidth=4    " 
set softtabstop=4	" number of spaces in tab when editing
set expandtab		" tabs are spaces

" makefile settings
autocmd FileType make setlocal noexpandtab      " for makefiles, tabs need to be actual tabs


"###### UI Config ######
set number relativenumber " show hybrid line numbers
set cursorline		" highlight current line
set wildmenu        " visual autocomplete
set showmatch       " highlights matching brackets
filetype indent on  " load filetype-specific indent files
